// AUTO-GENERATED by scripts/sync-menu.ts — do not edit by hand.
// Source: https://gist.github.com/nazt/741e431a81ff32afb509cade18408054
// Fetched: 2026-04-20T04:11:00.496Z
//
// To regenerate: `bun run sync:menu:gist` or `bun run sync:menu:api`
// To clear: `bun run sync:menu:reset`

import type { MenuApiItem } from './components/AppHeader/nav-types';

export interface BakedMenu {
  source: string;
  fetchedAt: string;
  items: MenuApiItem[];
}

const baked: BakedMenu = {
  source: "https://gist.github.com/nazt/741e431a81ff32afb509cade18408054",
  fetchedAt: "2026-04-20T04:11:00.496Z",
  items: [
  {
    "path": "/",
    "label": "Overview",
    "group": "main",
    "order": 10,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  },
  {
    "path": "/search",
    "label": "Search",
    "group": "main",
    "order": 20,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  },
  {
    "path": "/",
    "label": "Feed",
    "group": "main",
    "order": 30,
    "source": "api",
    "studio": "feed.buildwithoracle.com"
  },
  {
    "path": "/map",
    "label": "Memory",
    "group": "main",
    "order": 40,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  },
  {
    "path": "/",
    "label": "Forum",
    "group": "main",
    "order": 50,
    "source": "api",
    "studio": "forum.buildwithoracle.com"
  },
  {
    "path": "/activity",
    "label": "Activity",
    "group": "main",
    "order": 60,
    "source": "api",
    "studio": "studio.buildwithoracle.com",
    "query": {
      "tab": "searches"
    }
  },
  {
    "path": "/traces",
    "label": "Traces",
    "group": "main",
    "order": 70,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  },
  {
    "path": "/",
    "label": "Canvas",
    "group": "main",
    "order": 80,
    "source": "api",
    "studio": "canvas.buildwithoracle.com"
  },
  {
    "path": "/",
    "label": "Schedule",
    "group": "tools",
    "order": 110,
    "source": "api",
    "studio": "schedule.buildwithoracle.com"
  },
  {
    "path": "/pulse",
    "label": "Pulse",
    "group": "tools",
    "order": 120,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  },
  {
    "path": "/sessions",
    "label": "Sessions",
    "group": "tools",
    "order": 130,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  },
  {
    "path": "/plugins",
    "label": "Plugins",
    "group": "tools",
    "order": 140,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  },
  {
    "path": "/",
    "label": "Vector Playground",
    "group": "tools",
    "order": 150,
    "source": "api",
    "studio": "vector.buildwithoracle.com"
  },
  {
    "path": "/compare",
    "label": "Compare",
    "group": "tools",
    "order": 160,
    "source": "api",
    "studio": "vector.buildwithoracle.com"
  },
  {
    "path": "/evolution",
    "label": "Evolution",
    "group": "tools",
    "order": 170,
    "source": "api",
    "studio": "studio.buildwithoracle.com"
  }
] as unknown as MenuApiItem[],
};

export default baked;
