#!/usr/bin/env bun
/**
 * Sync menu JSON into packages/shared-ui/src/baked-menu.ts at build time.
 *
 * Usage:
 *   bun run scripts/sync-menu.ts --gist https://gist.github.com/nazt/<id>
 *   bun run scripts/sync-menu.ts --api http://localhost:47778/api/menu
 *   bun run scripts/sync-menu.ts --reset
 *
 * Output: rewrites packages/shared-ui/src/baked-menu.ts with a non-null default
 * export containing the fetched `{ items }`. Apps pick this up on the next
 * `bun run build`. No runtime fetch — purely build-time.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const BAKED_PATH = resolve(
  import.meta.dir,
  '..',
  'packages/shared-ui/src/baked-menu.ts',
);

type ParsedArgs = {
  source: 'gist' | 'api' | 'reset';
  url?: string;
};

function parseArgs(argv: string[]): ParsedArgs {
  if (argv.includes('--reset')) return { source: 'reset' };
  const gistIdx = argv.indexOf('--gist');
  if (gistIdx >= 0 && argv[gistIdx + 1]) return { source: 'gist', url: argv[gistIdx + 1] };
  const apiIdx = argv.indexOf('--api');
  if (apiIdx >= 0 && argv[apiIdx + 1]) return { source: 'api', url: argv[apiIdx + 1] };
  throw new Error(
    'Usage: sync-menu.ts --gist <gist-url> | --api <api-menu-url> | --reset',
  );
}

function toRawGistUrl(url: string): string {
  // gist.github.com/<user>/<id> → gist.githubusercontent.com/<user>/<id>/raw/
  const m = url.match(
    /^https?:\/\/gist\.github\.com\/([^/]+)\/([a-f0-9]+)(?:\/([a-f0-9]{7,64}))?/i,
  );
  if (!m) return url;
  const [, user, id, hash] = m;
  return hash
    ? `https://gist.githubusercontent.com/${user}/${id}/raw/${hash}/`
    : `https://gist.githubusercontent.com/${user}/${id}/raw/`;
}

async function fetchMenu(source: 'gist' | 'api', url: string): Promise<unknown> {
  const target = source === 'gist' ? toRawGistUrl(url) : url;
  const res = await fetch(target);
  if (!res.ok) throw new Error(`Fetch failed: ${target} → ${res.status}`);
  return res.json();
}

function writeBaked(content: string): void {
  writeFileSync(BAKED_PATH, content, 'utf8');
  console.log(`Wrote ${BAKED_PATH}`);
}

function resetBody(): string {
  return `// Build-time baked menu. Populated by \`bun run sync:menu:gist\` or \`bun run sync:menu:api\`.
// When null, apps fall back to DEFAULT_NAV in AppHeader.tsx.
// Never fetched at runtime — bundled into the app at build time for determinism + no-auto-reload.

import type { MenuApiItem } from './components/AppHeader/nav-types';

export interface BakedMenu {
  source: string;
  fetchedAt: string;
  items: MenuApiItem[];
}

const baked: BakedMenu | null = null;

export default baked;
`;
}

function bakedBody(source: string, items: unknown[]): string {
  const json = JSON.stringify(items, null, 2);
  return `// AUTO-GENERATED by scripts/sync-menu.ts — do not edit by hand.
// Source: ${source}
// Fetched: ${new Date().toISOString()}
//
// To regenerate: \`bun run sync:menu:gist\` or \`bun run sync:menu:api\`
// To clear: \`bun run sync:menu:reset\`

import type { MenuApiItem } from './components/AppHeader/nav-types';

export interface BakedMenu {
  source: string;
  fetchedAt: string;
  items: MenuApiItem[];
}

const baked: BakedMenu = {
  source: ${JSON.stringify(source)},
  fetchedAt: ${JSON.stringify(new Date().toISOString())},
  items: ${json} as unknown as MenuApiItem[],
};

export default baked;
`;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  if (args.source === 'reset') {
    writeBaked(resetBody());
    console.log('Baked menu reset — apps will use DEFAULT_NAV on next build.');
    return;
  }

  if (!args.url) throw new Error('--gist or --api requires a URL');

  console.log(`Fetching menu from ${args.source}: ${args.url}`);
  const data = await fetchMenu(args.source, args.url);

  if (!data || typeof data !== 'object' || !('items' in data)) {
    throw new Error('Fetched JSON missing `items` array');
  }
  const items = (data as { items: unknown }).items;
  if (!Array.isArray(items) || items.length === 0) {
    throw new Error('`items` must be a non-empty array');
  }

  writeBaked(bakedBody(args.url, items));
  console.log(`Baked ${items.length} menu items from ${args.source}.`);
  console.log('Next: `bun run build:all && bun run deploy:all`');
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
